# only allow specified users to cross-post (default false)
restrict_users: false

# list of users allowed to cross-post (only effective if restrict_users is true)

allowed_users:
  - "@user1:server.tld"
  - "@user2:server.tld"

# domain to be added to alias/room ID if not otherwise specified (normally your homeserver)
domain: "server.tld"

# template for cross-posting in the following format (default '[%on](%ol): %m \n\n (%b)')
# %on = original poster's display name
# %ol = link to original poster user ID
# %m = body of posting
# %e = emoji causing cross-post
# %bl = hyperlink to original post 
# %bu = display name of the user who caused the original post
# %bi = link to the cross-poster user ID
# %rn = room name of originating message
# \n = linebreak
template: "[%on](%ol): %m \n\n ([%e](%bl) by [%bu](%bi))"

# should messages be reposted to a room if they've already been posted once (default false)
repost: false

# send debug messages to maubot log file (default false)
debug: false
  
# allow plugin to cross-post messages from encrypted channels to unencrypted channels (default true)
insecure: true

# specify emoji followed by channel name (either alias or Room ID)
# format is emoji: channel_name
# channel-name can be
# - local alias (with or without leading #)
# - real room ID (with leading !)
mapping:
   🚋: 'public_transportation'
   💡: 'ideas'
