restrict_users: false
allowed_users:
  - "@user1:server.tld"
  - "@user2:server.tld"
# domain to be added to alias/room ID if not otherwise specified
domain: "server.tld"

# should messages be reposted to a room if they've already been posted once (normally you don't want this)
repost: false
  
# send debug messages to maubot log file
debug: false

# specify emoji followed by channel name (either alias or Room ID)
# format is emoji: channel_name
# channel-name can be
# - local alias (with or without leading #)
# - real room ID (with leading !)
mapping:
   🚋: 'public_transportation'
