restrict_users: false
allowed_users:
  - "@user1:server.tld"
  - "@user2:server.tld"
# domain to be added to alias/room ID if not otherwise specified
domain: "server.tld"
# specify emoji followed by channel name (either alias or Room ID)
mapping:
  - "train":"public_transportation"
